name: mi_tienda
description: Una aplicación de e-commerce con Flutter.
publish_to: 'none' # Evita publicar en pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.6.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Utils
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  cached_network_image: ^3.2.3

  # HTTP & JSON
  http: ^1.1.0
  intl: ^0.18.1

  # Voz
  speech_to_text: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1 # actualizada a versión más reciente
  permission_handler: ^11.3.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/placeholder.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
